[versions]
tomcat-embed-core = "11.0.9"
shadow = "9.0.0-rc3"
lombok = "1.18.38"
jackson-databind = "2.19.2"
jackson-datatype = "2.20.0-rc1"
spring-context = "7.0.0-M8"
spring-webmvc = "7.0.0-M8"
jackson-dataformat-xml = "2.20.0"
hibernate-validator = "9.0.0.Final"
expressly = "6.0.0"
thymeleaf-spring6 = "3.1.3.RELEASE"

[libraries]
tomcat-embed-core = { module = "org.apache.tomcat.embed:tomcat-embed-core", version.ref = "tomcat-embed-core" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson-databind" }
jackson-datatype = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson-datatype" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
spring-context = { module = "org.springframework:spring-context", version.ref = "spring-context" }
spring-webmvc = { module = "org.springframework:spring-webmvc", version.ref = "spring-webmvc" }
jackson-dataformat-xml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-xml", version.ref = "jackson-dataformat-xml" }
hibernate-validator = { module = "org.hibernate.validator:hibernate-validator", version.ref = "hibernate-validator" }
expressly = { module = "org.glassfish.expressly:expressly", version.ref = "expressly" }
thymeleaf-spring6 = { module = "org.thymeleaf:thymeleaf-spring6", version.ref = "thymeleaf-spring6" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
